generateOres = true
blacklistedOres = []
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = true
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
