[houses]
GENERATE_PLAINS_HOUSES = true
GENERATE_TAIGA_HOUSES = true
GENERATE_SAVANNA_HOUSES = true
GENERATE_SNOWY_HOUSES = true
GENERATE_DESERT_HOUSES = true
[weights]
WOODWORKER_HOUSE_WEIGHT = 15
OCEANOGRAPHER_HOUSE_WEIGHT = 15
FLORIST_HOUSE_WEIGHT = 15
HUNTER_HOUSE_WEIGHT = 15
ENGINEER_HOUSE_WEIGHT = 15
